import { useState } from "react";
import { FileDropzone } from "@/components/ui/FileDropzone";
import { ScanAnimation } from "@/components/ui/ScanAnimation";
import { RiskGauge } from "@/components/ui/RiskGauge";
import { Button } from "@/components/ui/button";
import { Download, RotateCcw, Shield, AlertTriangle, AlertCircle, Info } from "lucide-react";
import { toast } from "sonner";
import { useTranslation } from "@/hooks/useTranslation";
import { cn } from "@/lib/utils";

type ScanState = "idle" | "scanning" | "complete";

export default function Scan() {
  const [scanState, setScanState] = useState<ScanState>("idle");
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const { t, dir } = useTranslation();

  const handleFilesSelected = (files: File[]) => {
    setSelectedFiles(files);
  };

  const handleStartScan = () => {
    if (selectedFiles.length === 0) {
      toast.error(dir === "rtl" ? "الرجاء اختيار ملفات للفحص" : "Please select files to scan");
      return;
    }
    setScanState("scanning");
  };

  const handleScanComplete = () => {
    setScanState("complete");
    toast.success(dir === "rtl" ? "تم الفحص بنجاح!" : "Scan completed successfully!");
  };

  const handleReset = () => {
    setScanState("idle");
    setSelectedFiles([]);
  };

  const handleExportReport = () => {
    const report = `
SAFEGUARD AI - SECURITY SCAN REPORT
=====================================
Generated: ${new Date().toLocaleString()}
Files Scanned: ${selectedFiles.map(f => f.name).join(", ")}

SUMMARY
-------
Total Vulnerabilities: 0
- Critical: 0
- Medium: 0
- Low: 0

No vulnerabilities detected. Your code appears to be secure!

=====================================
Report generated by SafeGuard AI
    `;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `security-report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success(dir === "rtl" ? "تم تحميل التقرير بنجاح!" : "Report downloaded successfully!");
  };

  return (
    <div className={cn("space-y-8 animate-fade-in", dir === "rtl" && "text-right")} dir={dir}>
      {/* Header */}
      <div>
        <h1 className="text-2xl lg:text-3xl font-bold mb-2">
          {t.scan.title} <span className="gradient-text">{t.scan.titleHighlight}</span>
        </h1>
        <p className="text-muted-foreground">
          {t.scan.subtitle}
        </p>
      </div>

      {/* Idle State - File Upload */}
      {scanState === "idle" && (
        <div className="max-w-2xl mx-auto space-y-6">
          <FileDropzone onFilesSelected={handleFilesSelected} />
          
          {selectedFiles.length > 0 && (
            <Button
              onClick={handleStartScan}
              className="w-full bg-primary text-primary-foreground hover:bg-primary/90 h-12 text-lg glow-primary"
            >
              <Shield className={cn("h-5 w-5", dir === "rtl" ? "ml-2" : "mr-2")} />
              {t.scan.startScan}
            </Button>
          )}
        </div>
      )}

      {/* Scanning State */}
      {scanState === "scanning" && (
        <div className="max-w-xl mx-auto">
          <ScanAnimation isScanning={true} onComplete={handleScanComplete} />
        </div>
      )}

      {/* Complete State - Results */}
      {scanState === "complete" && (
        <div className="space-y-8">
          {/* Action Buttons */}
          <div className={cn("flex flex-wrap gap-4", dir === "rtl" ? "justify-start" : "justify-end")}>
            <Button variant="outline" onClick={handleReset}>
              <RotateCcw className={cn("h-4 w-4", dir === "rtl" ? "ml-2" : "mr-2")} />
              {t.scan.newScan}
            </Button>
            <Button onClick={handleExportReport} className="bg-primary text-primary-foreground hover:bg-primary/90">
              <Download className={cn("h-4 w-4", dir === "rtl" ? "ml-2" : "mr-2")} />
              {t.scan.exportReport}
            </Button>
          </div>

          {/* Results Summary */}
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Risk Gauge */}
            <div className="glass-panel p-6 flex flex-col items-center justify-center">
              <RiskGauge value={0} size="md" />
            </div>

            {/* Severity Breakdown */}
            <div className="lg:col-span-3 glass-panel p-6">
              <h2 className="text-lg font-semibold mb-4">{t.scan.vulnerabilitySummary}</h2>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className={cn("flex items-center gap-4 p-4 rounded-xl bg-destructive/10 border border-destructive/20", dir === "rtl" && "flex-row-reverse")}>
                  <div className="p-3 rounded-lg bg-destructive/20">
                    <AlertTriangle className="h-6 w-6 text-destructive" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-destructive">0</p>
                    <p className="text-sm text-muted-foreground">{t.common.critical}</p>
                  </div>
                </div>
                
                <div className={cn("flex items-center gap-4 p-4 rounded-xl bg-warning/10 border border-warning/20", dir === "rtl" && "flex-row-reverse")}>
                  <div className="p-3 rounded-lg bg-warning/20">
                    <AlertCircle className="h-6 w-6 text-warning" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-warning">0</p>
                    <p className="text-sm text-muted-foreground">{t.common.medium}</p>
                  </div>
                </div>
                
                <div className={cn("flex items-center gap-4 p-4 rounded-xl bg-success/10 border border-success/20", dir === "rtl" && "flex-row-reverse")}>
                  <div className="p-3 rounded-lg bg-success/20">
                    <Info className="h-6 w-6 text-success" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-success">0</p>
                    <p className="text-sm text-muted-foreground">{t.common.low}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* No Vulnerabilities Message */}
          <div className="glass-panel p-12 text-center">
            <div className="w-20 h-20 rounded-2xl bg-success/10 flex items-center justify-center mx-auto mb-6">
              <Shield className="h-10 w-10 text-success" />
            </div>
            <h3 className="text-xl font-semibold mb-2 text-success">
              {dir === "rtl" ? "الكود آمن!" : "Your Code is Secure!"}
            </h3>
            <p className="text-muted-foreground max-w-md mx-auto">
              {dir === "rtl" 
                ? "لم يتم العثور على ثغرات أمنية في الملفات التي تم فحصها. استمر في العمل الرائع!"
                : "No security vulnerabilities were found in the scanned files. Keep up the great work!"
              }
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
