import { useState } from "react";
import { FileDropzone } from "@/components/ui/FileDropzone";
import { ScanAnimation } from "@/components/ui/ScanAnimation";
import { RiskGauge } from "@/components/ui/RiskGauge";
import { VulnerabilityCard } from "@/components/ui/VulnerabilityCard";
import { mockVulnerabilities } from "@/data/mockVulnerabilities";
import { Button } from "@/components/ui/button";
import { Download, RotateCcw, Shield, AlertTriangle, AlertCircle, Info } from "lucide-react";
import { toast } from "sonner";

type ScanState = "idle" | "scanning" | "complete";

export default function Scan() {
  const [scanState, setScanState] = useState<ScanState>("idle");
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);

  const handleFilesSelected = (files: File[]) => {
    setSelectedFiles(files);
  };

  const handleStartScan = () => {
    if (selectedFiles.length === 0) {
      toast.error("Please select files to scan");
      return;
    }
    setScanState("scanning");
  };

  const handleScanComplete = () => {
    setScanState("complete");
    toast.success("Scan completed successfully!");
  };

  const handleReset = () => {
    setScanState("idle");
    setSelectedFiles([]);
  };

  const handleExportReport = () => {
    const criticalCount = mockVulnerabilities.filter(v => v.severity === "critical").length;
    const mediumCount = mockVulnerabilities.filter(v => v.severity === "medium").length;
    const lowCount = mockVulnerabilities.filter(v => v.severity === "low").length;

    const report = `
SAFEGUARD AI - SECURITY SCAN REPORT
=====================================
Generated: ${new Date().toLocaleString()}
Files Scanned: ${selectedFiles.map(f => f.name).join(", ")}

SUMMARY
-------
Total Vulnerabilities: ${mockVulnerabilities.length}
- Critical: ${criticalCount}
- Medium: ${mediumCount}
- Low: ${lowCount}

VULNERABILITIES FOUND
---------------------
${mockVulnerabilities.map(v => `
[${v.severity.toUpperCase()}] ${v.title}
Location: ${v.location}
Description: ${v.description}
Suggested Fix:
${v.suggestion}
`).join("\n---\n")}

=====================================
Report generated by SafeGuard AI
    `;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `security-report-${new Date().toISOString().split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    toast.success("Report downloaded successfully!");
  };

  const criticalCount = mockVulnerabilities.filter(v => v.severity === "critical").length;
  const mediumCount = mockVulnerabilities.filter(v => v.severity === "medium").length;
  const lowCount = mockVulnerabilities.filter(v => v.severity === "low").length;
  const riskScore = 68;

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div>
        <h1 className="text-2xl lg:text-3xl font-bold mb-2">
          AI Security <span className="gradient-text">Scanner</span>
        </h1>
        <p className="text-muted-foreground">
          Upload your code files or data logs for comprehensive security analysis
        </p>
      </div>

      {/* Idle State - File Upload */}
      {scanState === "idle" && (
        <div className="max-w-2xl mx-auto space-y-6">
          <FileDropzone onFilesSelected={handleFilesSelected} />
          
          {selectedFiles.length > 0 && (
            <Button
              onClick={handleStartScan}
              className="w-full bg-primary text-primary-foreground hover:bg-primary/90 h-12 text-lg glow-primary"
            >
              <Shield className="h-5 w-5 mr-2" />
              Start Security Scan
            </Button>
          )}
        </div>
      )}

      {/* Scanning State */}
      {scanState === "scanning" && (
        <div className="max-w-xl mx-auto">
          <ScanAnimation isScanning={true} onComplete={handleScanComplete} />
        </div>
      )}

      {/* Complete State - Results */}
      {scanState === "complete" && (
        <div className="space-y-8">
          {/* Action Buttons */}
          <div className="flex flex-wrap gap-4 justify-end">
            <Button variant="outline" onClick={handleReset}>
              <RotateCcw className="h-4 w-4 mr-2" />
              New Scan
            </Button>
            <Button onClick={handleExportReport} className="bg-primary text-primary-foreground hover:bg-primary/90">
              <Download className="h-4 w-4 mr-2" />
              Export Report
            </Button>
          </div>

          {/* Results Summary */}
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Risk Gauge */}
            <div className="glass-panel p-6 flex flex-col items-center justify-center">
              <RiskGauge value={riskScore} size="md" />
            </div>

            {/* Severity Breakdown */}
            <div className="lg:col-span-3 glass-panel p-6">
              <h2 className="text-lg font-semibold mb-4">Vulnerability Summary</h2>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="flex items-center gap-4 p-4 rounded-xl bg-destructive/10 border border-destructive/20">
                  <div className="p-3 rounded-lg bg-destructive/20">
                    <AlertTriangle className="h-6 w-6 text-destructive" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-destructive">{criticalCount}</p>
                    <p className="text-sm text-muted-foreground">Critical Issues</p>
                  </div>
                </div>
                
                <div className="flex items-center gap-4 p-4 rounded-xl bg-warning/10 border border-warning/20">
                  <div className="p-3 rounded-lg bg-warning/20">
                    <AlertCircle className="h-6 w-6 text-warning" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-warning">{mediumCount}</p>
                    <p className="text-sm text-muted-foreground">Medium Issues</p>
                  </div>
                </div>
                
                <div className="flex items-center gap-4 p-4 rounded-xl bg-success/10 border border-success/20">
                  <div className="p-3 rounded-lg bg-success/20">
                    <Info className="h-6 w-6 text-success" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-success">{lowCount}</p>
                    <p className="text-sm text-muted-foreground">Low Issues</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Vulnerabilities List */}
          <div className="space-y-4">
            <h2 className="text-lg font-semibold">Detected Vulnerabilities</h2>
            <div className="space-y-3">
              {mockVulnerabilities.map((vuln, index) => (
                <VulnerabilityCard key={vuln.id} vulnerability={vuln} index={index} />
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
